matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1
      solution: Ahorcado.sln
      script:
        - dotnet restore
        - dotnet test /p:CollectCoverage=true 
    
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - node_modules
      script:
        - npm test  -- --coverage --watchAll=false
        - npm run build
      before_install:
        - cd client-app
