// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201027231623_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Domain.Juego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantIntentos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Palabra")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntaje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Juegos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantIntentos = 6,
                            Modelo = "_ _ _ _ _ _ _ _ _",
                            Palabra = "automovil",
                            Puntaje = 0,
                            Usuario = "Pepe"
                        });
                });

            modelBuilder.Entity("Domain.LetraIngresada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JuegoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Letra")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JuegoId");

                    b.ToTable("LetraIngresadas");
                });

            modelBuilder.Entity("Domain.LetraIngresada", b =>
                {
                    b.HasOne("Domain.Juego", "Juego")
                        .WithMany("LetrasIngresadas")
                        .HasForeignKey("JuegoId");
                });
#pragma warning restore 612, 618
        }
    }
}
